#!/bin/bash -e

# Usage
export PATH=/usr/local/bin:/usr/local/bins:/usr/bin:/usr/sbin:/bin:/sbin
if [ $# -ne 1 ]; then
  echo "Usage $0 <pfx>"
  exit 1
fi
pfx=$1
set +x

openssl pkcs12 -in ${pfx} -nocerts -out `basename -s .pfx ${pfx}`-key.pem -nodes
openssl pkcs12 -in ${pfx} -nokeys -out `basename -s .pfx ${pfx}`-cert.pem -nodes
