#!/bin/bash -e

# Usage
export PATH=/usr/local/bin:/usr/local/bins:/usr/bin:/usr/sbin:/bin:/sbin
if [ $# -ne 1 ]; then
  echo "Usage $0 <key>"
  exit 1
fi
key=$1
set +x

base=`basename -s .pem ${key}`
openssl rsa -in ${key} -out ${key}-nopassword.pem

